
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Johnny Rodriguez H. 
 */
public class EjemploTimer extends javax.swing.JFrame {

    /**
     * Creates new form EjemploTimer
     */
    public EjemploTimer() {

        initComponents();

        this.setTitle("Realizado por Johnny Rodríguez H.");
        setLocationRelativeTo(null);
        tiempo = new Timer(1000, tarea);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_iniciar = new javax.swing.JButton();
        txt_h = new javax.swing.JTextField();
        txt_m = new javax.swing.JTextField();
        txt_s = new javax.swing.JTextField();
        btn_pausar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_detener = new javax.swing.JButton();
        jPanel = new javax.swing.JPanel();
        lbl_s2 = new javax.swing.JLabel();
        lbl_s1 = new javax.swing.JLabel();
        lbl_m2 = new javax.swing.JLabel();
        lbl_m1 = new javax.swing.JLabel();
        lbl_h2 = new javax.swing.JLabel();
        lbl_h1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btn_iniciar.setText("Iniciar");
        btn_iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iniciarActionPerformed(evt);
            }
        });

        txt_h.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_hFocusLost(evt);
            }
        });
        txt_h.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_hKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_hKeyTyped(evt);
            }
        });

        txt_m.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_mFocusLost(evt);
            }
        });
        txt_m.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_mKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_mKeyTyped(evt);
            }
        });

        txt_s.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_sFocusLost(evt);
            }
        });
        txt_s.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_sKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_sKeyTyped(evt);
            }
        });

        btn_pausar.setText("Pausar");
        btn_pausar.setEnabled(false);
        btn_pausar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pausarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Hrs");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Mins");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Secs");

        btn_detener.setText("Detener");
        btn_detener.setEnabled(false);
        btn_detener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_detenerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_h)
                .addGap(18, 18, 18)
                .addComponent(txt_m)
                .addGap(18, 18, 18)
                .addComponent(txt_s)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_pausar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_detener))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btn_iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_h, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_s, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_iniciar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_pausar)
                    .addComponent(btn_detener))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel.setBackground(new java.awt.Color(204, 153, 255));
        jPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lbl_s2.setBackground(new java.awt.Color(255, 255, 255));
        lbl_s2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_s1.setBackground(new java.awt.Color(255, 255, 255));
        lbl_s1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_m2.setBackground(new java.awt.Color(255, 255, 255));
        lbl_m2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_m1.setBackground(new java.awt.Color(255, 255, 255));
        lbl_m1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_h2.setBackground(new java.awt.Color(255, 255, 255));
        lbl_h2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_h1.setBackground(new java.awt.Color(255, 255, 255));
        lbl_h1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText(":");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText(":");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Hrs");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Mins");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Secs");

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(lbl_h1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_h2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_m1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_m2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel5)
                .addGap(4, 4, 4)
                .addComponent(lbl_s1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_s2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel6)
                .addGap(61, 61, 61)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(47, 47, 47))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(3, 3, 3)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_h2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_h1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_m2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_m1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_s2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_s1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Timer tiempo;
    private final ActionListener tarea = new ActionListener() {

        @Override
        public void actionPerformed(ActionEvent ae) {

            txt_h.setEditable(false);
            txt_m.setEditable(false);
            txt_s.setEditable(false);

            int h = Integer.parseInt(txt_h.getText());
            int m = Integer.parseInt(txt_m.getText());
            int s = Integer.parseInt(txt_s.getText());

            s--;
            System.out.println("Secs: " + s);

            if (s <= -1) {
                m--;
                System.out.println("Mins: " + m);
                s = 59;
            }

            if (m < 0) {
                h--;
                System.out.println("Hrs: " + h);
                m = 59;
            }

            if (h < 0) {
                tiempo.stop();
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(null, "Tiempo Finalizado");

                txt_h.setText("");
                txt_m.setText("");
                txt_s.setText("");

                txt_h.setEditable(true);
                txt_m.setEditable(true);
                txt_s.setEditable(true);

                txt_h.requestFocus();

                btn_iniciar.setEnabled(true);
                btn_iniciar.setText("Iniciar");

                btn_pausar.setEnabled(false);
                btn_detener.setEnabled(false);

                lbl_h1.setIcon(new ImageIcon(getClass().getResource("/Iconos" + "/" + 0 + ".png")));
                lbl_h2.setIcon(new ImageIcon(getClass().getResource("/Iconos" + "/" + 0 + ".png")));

                lbl_m1.setIcon(new ImageIcon(getClass().getResource("/Iconos" + "/" + 0 + ".png")));
                lbl_m2.setIcon(new ImageIcon(getClass().getResource("/Iconos" + "/" + 0 + ".png")));

                lbl_s1.setIcon(new ImageIcon(getClass().getResource("/Iconos" + "/" + 0 + ".png")));
                lbl_s2.setIcon(new ImageIcon(getClass().getResource("/Iconos" + "/" + 0 + ".png")));

                return;
            }

            int s1 = s / 10; // Si 2 números enteros se dividen la division se hace como números enteros por lo q queda sin decimales  
            System.out.println("s1: " + s1);

            int s2 = s % 10;
            System.out.println("s2: " + s2);

            int m1 = m / 10;
            int m2 = m % 10;

            int h1 = h / 10;
            int h2 = h % 10;

            lbl_h1.setIcon(new ImageIcon(getClass().getResource("/Iconos" + "/" + h1 + ".png")));
            lbl_h2.setIcon(new ImageIcon(getClass().getResource("/Iconos" + "/" + h2 + ".png")));

            lbl_m1.setIcon(new ImageIcon(getClass().getResource("/Iconos" + "/" + m1 + ".png")));
            lbl_m2.setIcon(new ImageIcon(getClass().getResource("/Iconos" + "/" + m2 + ".png")));

            lbl_s1.setIcon(new ImageIcon(getClass().getResource("/Iconos" + "/" + s1 + ".png")));
            lbl_s2.setIcon(new ImageIcon(getClass().getResource("/Iconos" + "/" + (s2 < 0 ? "0" : s2) + ".png")));

            txt_h.setText(h + "");
            txt_m.setText(m + "");
            txt_s.setText(s + "");
        }
    };

    private void btn_iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iniciarActionPerformed

        if (!(txt_m.getText().isEmpty())) {
            if (!(txt_s.getText().isEmpty())) {

                tiempo.start(); 

                btn_iniciar.setEnabled(false);
                btn_iniciar.setText("Renaudar");
                btn_pausar.setEnabled(true);
                btn_detener.setEnabled(true); 

            } else {
                Toolkit.getDefaultToolkit().beep();
                txt_s.setText(0 + "");
                JOptionPane.showMessageDialog(null, "Sesc asignado a 0 \nPrecione iniciar para continuar", "Mensaje de advertencia", JOptionPane.INFORMATION_MESSAGE);

            }
        } else {
            Toolkit.getDefaultToolkit().beep();
            txt_m.setText(0 + "");
            JOptionPane.showMessageDialog(null, "Min asignado a 0 \nPrecione iniciar para continuar", "Mensaje de advertencia", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_iniciarActionPerformed

    private void txt_hKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_hKeyTyped

        int c = evt.getKeyChar();
        //         0          9      delete
        if ((c >= 48 && c <= 58) || (c == 8)) {
        } else {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }

        int cantidad = txt_h.getText().trim().length();
        if (cantidad >= 2) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txt_hKeyTyped

    private void txt_mKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_mKeyTyped
        int c = evt.getKeyChar();
        //         0          9      delete
        if ((c >= 48 && c <= 58) || (c == 8)) {
        } else {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }

        int cantidad = txt_m.getText().trim().length();
        if (cantidad >= 2) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txt_mKeyTyped

    private void txt_sKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_sKeyTyped
        int c = evt.getKeyChar();
        //         0          9      delete
        if ((c >= 48 && c <= 58) || (c == 8)) {
        } else {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }

        int cantidad = txt_s.getText().trim().length();
        if (cantidad >= 2) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txt_sKeyTyped

    private void txt_hFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_hFocusLost
        if (!txt_h.getText().isEmpty()) { // condicion para arreglar Exception in thread "AWT-EventQueue-0" java.lang.NumberFormatException: For input string: ""
            int b = Integer.parseInt(txt_h.getText().trim());
            // El método de length de cadena devuelve la cantidad de caracteres escritos en la Cadena.
            if ((b > 99 || b < 0)) {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(null, "Rango no valido", "Mensaje de advertencia", JOptionPane.INFORMATION_MESSAGE);
                txt_h.setText(0 + "");
            }
        } else {
            txt_h.setText(0 + "");
        }
    }//GEN-LAST:event_txt_hFocusLost

    private void txt_mFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_mFocusLost
        if (!txt_m.getText().isEmpty()) { // condicion para arreglar Exception in thread "AWT-EventQueue-0" java.lang.NumberFormatException: For input string: ""
            int b = Integer.parseInt(txt_m.getText().trim());
            // El método de length de cadena devuelve la cantidad de caracteres escritos en la Cadena.
            if ((b > 59 || b < 0)) {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(null, "Rango no valido", "Mensaje de advertencia", JOptionPane.INFORMATION_MESSAGE);
                txt_m.setText(0 + "");
                txt_s.setText(0 + "");
            }
        } else {
            txt_m.setText(0 + "");
        }
    }//GEN-LAST:event_txt_mFocusLost

    private void txt_sFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_sFocusLost
        if (!txt_s.getText().isEmpty()) { // condicion para arreglar Exception in thread "AWT-EventQueue-0" java.lang.NumberFormatException: For input string: ""
            int b = Integer.parseInt(txt_s.getText().trim());
            // El método de length de cadena devuelve la cantidad de caracteres escritos en la Cadena.
            if ((b > 59 || b < 0)) {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(null, "Rango no valido", "Mensaje de advertencia", JOptionPane.INFORMATION_MESSAGE);
                txt_s.setText(0 + "");
            }
        } else {
            txt_s.setText(0 + "");
        }
    }//GEN-LAST:event_txt_sFocusLost

    private void btn_pausarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pausarActionPerformed

        tiempo.stop();

        btn_iniciar.setEnabled(true);
        btn_pausar.setEnabled(false);
    }//GEN-LAST:event_btn_pausarActionPerformed

    private void btn_detenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_detenerActionPerformed

        if (tiempo.isRunning()) {
            tiempo.stop();
            btn_iniciar.setEnabled(true);
        }
        btn_iniciar.setText("Iniciar");
        btn_pausar.setEnabled(false);
        btn_detener.setEnabled(false);

        txt_h.setText("");
        txt_m.setText("");
        txt_s.setText("");

        txt_h.setEditable(true);
        txt_m.setEditable(true);
        txt_s.setEditable(true);

        txt_h.requestFocus();

        lbl_h1.setIcon(new ImageIcon(getClass().getResource("/Iconos" + "/" + 0 + ".png")));
        lbl_h2.setIcon(new ImageIcon(getClass().getResource("/Iconos" + "/" + 0 + ".png")));

        lbl_m1.setIcon(new ImageIcon(getClass().getResource("/Iconos" + "/" + 0 + ".png")));
        lbl_m2.setIcon(new ImageIcon(getClass().getResource("/Iconos" + "/" + 0 + ".png")));

        lbl_s1.setIcon(new ImageIcon(getClass().getResource("/Iconos" + "/" + 0 + ".png")));
        lbl_s2.setIcon(new ImageIcon(getClass().getResource("/Iconos" + "/" + 0 + ".png")));

    }//GEN-LAST:event_btn_detenerActionPerformed

    private void txt_hKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_hKeyPressed

        if (evt.isControlDown()) {
            evt.consume(); //Cancela la tecla precionada
            Toolkit.getDefaultToolkit().beep(); //Sonido de mensaje de error  

            JOptionPane.showMessageDialog(null, "Control deshabilitado\n Ingrese por teclado", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_txt_hKeyPressed

    private void txt_mKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_mKeyPressed
        if (evt.isControlDown()) {
            evt.consume(); //Cancela la tecla precionada
            Toolkit.getDefaultToolkit().beep(); //Sonido de mensaje de error  

            JOptionPane.showMessageDialog(null, "Control deshabilitado\n Ingrese por teclado", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_txt_mKeyPressed

    private void txt_sKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_sKeyPressed
        if (evt.isControlDown()) {
            evt.consume(); //Cancela la tecla precionada
            Toolkit.getDefaultToolkit().beep(); //Sonido de mensaje de error  

            JOptionPane.showMessageDialog(null, "Control deshabilitado\n Ingrese por teclado", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_txt_sKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EjemploTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EjemploTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EjemploTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EjemploTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EjemploTimer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_detener;
    private javax.swing.JButton btn_iniciar;
    private javax.swing.JButton btn_pausar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_h1;
    private javax.swing.JLabel lbl_h2;
    private javax.swing.JLabel lbl_m1;
    private javax.swing.JLabel lbl_m2;
    private javax.swing.JLabel lbl_s1;
    private javax.swing.JLabel lbl_s2;
    private javax.swing.JTextField txt_h;
    private javax.swing.JTextField txt_m;
    private javax.swing.JTextField txt_s;
    // End of variables declaration//GEN-END:variables
}
